[project]
name = "knowsynth"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=3.6.0",
    "huggingface-hub>=0.32.2",
    "pandas>=2.2.3",
]
